### PR TITLE
[TEST FIRST] Cheat editor improvements

### PR DESCRIPTION
**Pull request by easyaspi314**
Sorry about the web commits. AIDE (Android Eclipse/AS equivalent) wouldn't cooperate. You can squash the commits if you wish.

I can't compile right now. Can somebody test? @fzurita? 

* When the code is invalid, the OK button grays out as well as be disabled
* Case insensitivity. The cheat engine, I found, is 100% case insensitive, and many hex codes are also done in lowercase. This should work.
* Layout improvements: Dialog resizes to the keyboard, and should scroll/resize properly.

### CODE REVIEW

**Comment by fzurita** [comment]
Interesting, I'll take a look at this once u very a chance.

**Comment by easyaspi314** [comment]
OK so I am on home WiFi, and found out that the Git errors are likely because of a bad cloning; I was missing a few files. 
Because I am on WiFi, I am also installing NDK into AIDE.

**Comment by fzurita** [comment]
Ok, cool. I'll run what you have and see what I get.

**Comment by fzurita** [comment]
Ok, I looked at your changes. They all look correct. I'll see how they improve the layout.

**Comment by fzurita** [comment]
Ok, this is not bad work. There is one issue though, the getColor method you used in for example EditCheatDialog only applies to API level 23 which is only newer devices. Our minimum API is level 15 which is android kitkat.

When the getColor method gets called in kitkat, the app crashes. You just have to find a different way to get those colors.

Here is an easy fix, replace ```getActivity.getColor``` with

```
ContextCompat.getColor(getActivity(), R.color.accent_material_dark)
```

**Comment by easyaspi314** [comment]
Hmm. Good idea. However, I think getColor(int) was *deprecated* in 23 in favor of getColor(int, Theme). ContextCompat will work.

**Comment by fzurita** [comment]
Interesting, eclipse was complaining about the getColor method only being supported in API level 23 or greater.

**Comment by easyaspi314** [comment]
Whoops, getResources().getColor() was deprecated. I committed the fix.

**Comment by fzurita** [comment]
Cool, can you squash your commits? I think after that it's good to go.

**Comment by easyaspi314** [comment]
You wanna do that? My computer isn't working. You will have write access in
a moment.

**Comment by fzurita** [comment]
Yeah, I can do it. Don't worry about giving me wire access, I can do a rebase from my local copy before committing to master.

**Comment by easyaspi314** [comment]
Too late

**Comment by easyaspi314** [comment]
I am about to change the edittexts to all caps.

**Comment by easyaspi314** [comment]
Commits are up.

**Comment by fzurita** [comment]
Ok

**Comment by easyaspi314** [comment]
Does it compile? I can test an APK if needed.

**Comment by fzurita** [comment]
Yep, it compiles. In the process of merging. It should show up in the auto builds in around an hour.

**Comment by fzurita** [comment]
Well, almost compiled. You were missing the getActivity() argument in getColor(). I'll fix it before merging.

**Comment by fzurita** [comment]
Everything is merged and committed. Closing.

**Comment by easyaspi314** [comment]
Ack. It crashes when I type anything in advanced cheat mode and the cursor is weird.

But the stack trace, oddly, shows **nothing** related to m64+. The traceback shows no signs of m64+. Nothing. All of the classes mentioned are under the Android classes.

Might be XML.

**Comment by easyaspi314** [comment]
```console
D/AbsListView(24826): onDetachedFromWindow
I/AppCompatDelegate(24826): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
E/ViewRootImpl(24826): sendUserActionEvent() mView == null
D/AndroidRuntime(24826): Shutting down VM
W/dalvikvm(24826): threadid=1: thread exiting with uncaught exception (group=0x418d6da0)
D/dalvikvm(24826): GC_CONCURRENT freed 6489K, 24% free 27791K/36276K, paused 4ms+10ms, total 171ms
D/dalvikvm(24826): WAIT_FOR_CONCURRENT_GC blocked 101ms
E/AndroidRuntime(24826): FATAL EXCEPTION: main
E/AndroidRuntime(24826): Process: org.mupen64plusae.v3.alpha, PID: 24826
E/AndroidRuntime(24826): java.lang.StringIndexOutOfBoundsException: length=168; index=168
E/AndroidRuntime(24826): 	at java.lang.String.indexAndLength(String.java:584)
E/AndroidRuntime(24826): 	at java.lang.String.charAt(String.java:578)
E/AndroidRuntime(24826): 	at android.text.Layout.getLineVisibleEnd(Layout.java:1174)
E/AndroidRuntime(24826): 	at android.text.Layout.drawText(Layout.java:245)
E/AndroidRuntime(24826): 	at android.widget.Editor.drawHardwareAccelerated(Editor.java:1621)
E/AndroidRuntime(24826): 	at android.widget.Editor.onDraw(Editor.java:1544)
E/AndroidRuntime(24826): 	at android.widget.TextView.onDraw(TextView.java:6416)
E/AndroidRuntime(24826): 	at android.view.View.draw(View.java:15410)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14301)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3283)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14238)
E/AndroidRuntime(24826): 	at android.view.View.getDisplayList(View.java:14343)
E/AndroidRuntime(24826): 	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
E/AndroidRuntime(24826): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
E/AndroidRuntime(24826): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2777)
E/AndroidRuntime(24826): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2643)
E/AndroidRuntime(24826): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
E/AndroidRuntime(24826): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
E/AndroidRuntime(24826): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6632)
E/AndroidRuntime(24826): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
E/AndroidRuntime(24826): 	at android.view.Choreographer.doCallbacks(Choreographer.java:614)
E/AndroidRuntime(24826): 	at android.view.Choreographer.doFrame(Choreographer.java:584)
E/AndroidRuntime(24826): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
E/AndroidRuntime(24826): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(24826): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(24826): 	at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime(24826): 	at android.app.ActivityThread.main(ActivityThread.java:5487)
E/AndroidRuntime(24826): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(24826): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(24826): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/AndroidRuntime(24826): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/AndroidRuntime(24826): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(24826): 	at dalvik.system.NativeStart.main(Native Method)
I/Process (24826): Sending signal. PID: 24826 SIG: 9
I/ActivityManager(  838): Process org.mupen64plusae.v3.alpha (pid 24826) (adj 0) has died.
W/InputMethodManagerService(  838): Got RemoteException sending setActive(false) notification to pid 24826 uid 10098
```

**Comment by fzurita** [comment]
Amusing crash. I hate this kind. I'll put some debug points to figure out where it is happening. I suspect it's the cheat validation since it happened after attempting to input something.

**Comment by fzurita** [comment]
Ok, here is the problem:

http://stackoverflow.com/questions/28644616/android-edittext-gives-indexoutofbounds-exception-while-using-textallcaps

**Comment by fzurita** [comment]
We shouldn't use textAllCaps in an EditText, only in a TextView. You are supposed to use android:inputType="textCapCharacters" which I'm already using.

**Comment by fzurita** [comment]
Ok, fix has been committed. There is an odd new issue though. If you enter any characters that are not part of the allowed characters, then enter a character that belongs, the whole line gets copied and pasted... Very odd...

**Comment by fzurita** [comment]
The odd issue with text entry was due to the keyboard I was using. Disabling spell check fixes the issue so I did that as well since you don't really need that for cheats.

**Pull request closed without merging**
