### PR TITLE
Mupen64plus core interaction enhancements and UI enhancements

### PR DESCRIPTION
**Pull request by fzurita**
* Gameplay will be restored automatically and the sidebar closed if a slot or file is loaded or saved. This involved fixing a lot of corner cases.

* The gallery game side bar is now closed automatically when launching a game. This forces a refresh of the gallery sidebar so the the resume button shows up when a game is opened for the first time.

* Now no longer showing the toast staying that a game is being resumed when a game is being restarted. This is done correctly this time.

* We will now no longer exit the GameActivity immediately after a user chooses to exit. We will now wait until the core is done fully shutting down.

* Added a reset option to the in-game sidebar.

### CODE REVIEW

**Comment by Gillou68310** [comment]
I noticed some wrong cases:
- If selecting the exit item then canceling on prompt confirmation, game resumes while game sidebar is still opened
- If game sidebar is opened and home button is pressed, restoring app will resume game while sidebar is still opened

 I think the sidebar should also be closed if saving a slot or file, what do you think?

**Comment by fzurita** [comment]
Nice testing. Thanks for finding those cases.

Also, yeah, it probably makes sense to close the side bar in those cases as well.

**Comment by fzurita** [comment]
I see the problem with with the emulator resuming when the home button is hit and then we go back to the app. The ```GameSurface.createGLContext()``` we resume the emulator if it's currently not in the running state.

This also means that if the user pauses the emulator using an assigned controller key, if they hit the home button and come back to the app, the emulator will come back as unpaused. I can't think of any other case where it will break.

**Comment by fzurita** [comment]
This should be good to go now, I'm going to look at the crashing and save state not loading issues when moving the toast next.

**Comment by Gillou68310** [comment]
Still one issue, if you press the sleep button and sidebar is closed, when waking up the phone the emulation doesn't resume.

Also doing an advanceFrame() when surface is recreated is a good idea but it doesn't seems to work for every game I tested.

Another option is to save the framebuffer to texture and draw that texture when egl surface is recreated, but that's a lot of work for nothing IMO.

The easiest solution for now would be to just close the sidebar (and possibly opened dialog) and resume the game, what do you think?

**Comment by fzurita** [comment]
What game for advance frame not work with? Maybe advancing 2 frames will work with all games.

**Comment by fzurita** [comment]
Hmm... redrawing the menu when gallary comes back up after exiting a game doesn't quite work because the save hasn't happened yet.

**Comment by Gillou68310** [comment]
> What game does advance frame not work with? Maybe advancing 2 frames will work with all games.

Rayman2 and I tried advancing 3 frames it still doesn't work :-(

> The only easy solution I can think of is to add an Async task that just waits 1 second and then checks for the presence of any auto saves after exiting a game. The other option is to just assume that an auto save will be present after exiting a game.

Maybe you can force the sidebar to close only on game exit?

**Comment by fzurita** [comment]
Yeah, that's probably a better option. I can close the sidebar if a game is launched either through re-start or resume.

**Comment by Gillou68310** [comment]
Just make sure the closing is done after the game surface is created, just to be sure it's not visible to the user.

**Comment by fzurita** [comment]
I had a segfault from the core when loading Rayman 2 for the first time. See here:

https://drive.google.com/file/d/0B57Ioy26LWegQlpmQnV1MDJ0VnM/view?usp=sharing

**Comment by Gillou68310** [comment]
You mean when exiting rayman for the first time?

**Comment by fzurita** [comment]
Yes, it did happen while trying to exit.

**Comment by Gillou68310** [comment]
Is this still happening?

**Comment by fzurita** [comment]
It only happened the first time I tried to load then quickly exit the game.

**Comment by fzurita** [comment]
I didn't let it finish loading though.

**Comment by Gillou68310** [comment]
Your log is weird because the egl context is created 2 times I don't understand how this happens!

**Comment by Gillou68310** [comment]
Does it happens on this branch or master?

**Comment by fzurita** [comment]
Just this branch.

**Comment by Gillou68310** [comment]
Maybe a race condition with the game surface listener

**Comment by Gillou68310** [comment]
Do some more testing and just see if it happens again

**Comment by fzurita** [comment]
Try opening a game that you haven't opened before. And before it's done loading, exit the game. That's when this happened to me.

**Comment by Gillou68310** [comment]
I think this is what caused the crash:
11-06 11:33:27.326: I/GameLifecycleHandler(31347): onCreate

How on earth did the GameLifecycleHandler got re-created?

**Comment by fzurita** [comment]
It will be re-created each time a game is launched.

**Comment by Gillou68310** [comment]
Sure but not while the game is already running!

**Comment by fzurita** [comment]
I think I know what's happening. It's because the Core runs in another thread. So if I run a game and exit it, which brings me back to the gallery, but the core is still running in the background. Then I very quickly launch another game before the core is done exiting....

**Comment by fzurita** [comment]
I don't think the CoreInterface.shutdownEmulator() is really waiting for the core to shut down before showing the gallery again.

**Comment by Gillou68310** [comment]
No it's not I already noticed that

**Comment by Gillou68310** [comment]
Maybe we should wait until core is finished before calling a finish activity

**Comment by fzurita** [comment]
And this is happening because the CoreInterface.exit() call is killing the GameActivity. The GameLifecycleHandler.onDestroy method is being called while the Gallery is up in the background.

**Comment by Gillou68310** [comment]
Yep ;-)

**Comment by Gillou68310** [comment]
That was intended by the way

**Comment by fzurita** [comment]
The easy fix is to only call sActivity.finish in the shutdownEmulator call. I would really just combine the CoreInterface.exit and CoreInterface.shutdownEmulator methods. Then nothing at all would get called in onDestroy.

**Comment by Gillou68310** [comment]
I did that at some point but reverted it I can't remember why.
Ok let's do this and see what's happening

**Comment by fzurita** [comment]
I think I know why. It would add a considerable delay when exiting the emulator. Maybe the right answer is to make sure that the core is still not running when launching a new game.

**Comment by fzurita** [comment]
Hmm... I don't get a black screen in Rayman 2 when going home and coming back to the app in my 4.4 device either. Can you check if the issue is still happening to you with the newest version of this branch?

**Comment by Gillou68310** [comment]
> I think I know why. It would add a considerable delay when exiting the emulator. Maybe the right answer is to make sure that the core is still not running when launching a new game.

Sounds like a good idea but that would required communication between gallery activity and game activity like you said earlier.

> Hmm... I don't get a black screen in Rayman 2 when going home and coming back to the app in my 4.4 device either. Can you check if the issue is still happening to you with the newest version of this branch?

Give me a sec

**Comment by Gillou68310** [comment]
Ok black screen only occurs if framebuffer emulation is disable, so it may not work with other video plugins as well (haven't checked)

If you're in portrait mode, start a game in landscape mode then exit the game while still in landscape mode the gallery sidebar isn't closing.

Going back home I won't be able to do more tests until tomorrow ;-)

**Comment by fzurita** [comment]
You are good at finding all the corner cases.

**Comment by Gillou68310** [comment]
They usually find me first ;-)

> I think I know why. It would add a considerable delay when exiting the emulator. Maybe the right answer is to make sure that the core is still not running when launching a new game.

Just got an idea, doing a finish activity when core thread  is finished should possibly fix the swap buffer exception you get on your device. But surely will add a delay when exiting :-(

**Comment by fzurita** [comment]
I agree, it will fix that. It is also going to add a good amount of delay when exiting a game.

**Comment by fzurita** [comment]
I just realized that all the toast messages in CoreInterface.startupEmulator will crash the app because they are all being called outside the main UI thread

**Comment by fzurita** [comment]
I went ahead and took a crack at it. I don't really see much difference in how long it takes to exit.

**Comment by littleguy77** [comment]
Wow... most github notifications in a day LOL

Glad to see I'm not the only one who pulled his hair out trying to figure out the lifecycle mechanics!  The number of corner cases is astonishing.  There are a bazillion use case sequences.  Add to that the variations between different Android versions.  This is why I always got nervous when @Gillou68310 brought up the "don't destroy GL context" branch... ;)  Took me forever just to get something that didn't crash.

I am so far out of this particular conversation, so I won't try to steer you in any way.  Just wanted to share some of my experiences.  IIRC, I eventually found that the only way I could "win" was to treat the Android lifecycle as master, and slave the OpenGL and core lifecycles to it.  Whenever I viewed the core's lifecycle as the master, things usually seemed to spiral down a rabbit hole.  Patch a corner case only to reveal another...

**Comment by fzurita** [comment]
I know... Even a minor change in this area of the code seems to break something else. I think we are getting there though.

**Comment by littleguy77** [comment]
Cool.  Quick question, is the purpose of this PR still "Opening the in-game sidebar now pauses gameplay", or has it evolved to do more?  Just wondering because sounds like a lot of effort and changes for a seemingly minor UX enhancement.

**Comment by fzurita** [comment]
It really has evolved significantly. I'm sure you gather that by the conversation. Just to get this working correctly has meant a lot of changes.

**Comment by littleguy77** [comment]
Yes, the implementation has evolved significantly.  What I'm unclear on is whether the *feature* that this PR implements is still merely to pause the emulator when sidebar is open.  If this PR now implements several new features besides just pausing the emulator, please update the title or first comment at the top of this page.  Thanks ;)

**Comment by fzurita** [comment]
Yep, of course :)

**Comment by Gillou68310** [comment]
> Still one issue, if you press the sleep button and sidebar is closed, when waking up the phone the emulation doesn't resume.

This is still an issue.

Also I suggest adding a dialog when selecting the "reset" option, so users don't lose their progress if accidentaly touching the option.

Everything else look good, nice work ;-)

**Comment by Gillou68310** [comment]
We still need to do something about the advance frame thing, but this is not a functionnal issue so it can be done later.

**Comment by fzurita** [comment]
Hmmm, I thought I fixed that... Looks like I broke it again. I think I know what's wrong though. I'll also add the confirmation dialog.

**Comment by fzurita** [comment]
Which plugin had the advanced frame issue?

**Comment by Gillou68310** [comment]
gliden64 has it with framebuffer emulation off, I haven't checked the others

**Comment by xperia64** [comment]
I just tried the latest autobuild from 11-04 and the orientation option seems to be missing.

**Comment by fzurita** [comment]
Hmmm, interesting. Where s this option located? I haven't really messed around much with it.

**Comment by fzurita** [comment]
I see the option under app settings.

**Comment by xperia64** [comment]
Oh yep it's there. I just was used to it being next to the resolution settings which are now per-game.

**Comment by fzurita** [comment]
Ok. The restart confirmation dialog has been added. Also I again fixed the case where we would not resume correctly if a device was suspended.

**Comment by fzurita** [comment]
This branch has gotten really messy in the commit history. Before you merge it, I'm going change history to make it neater.

**Comment by fzurita** [comment]
Ok, I'm done redoing the commit history.

**Pull request merged**
