### PR TITLE
Google Play Store Ratings

### PR DESCRIPTION
**Pull request by ogtimothymiller**
Added rating dialog

### CODE REVIEW

**Comment by fzurita** [comment]
This is just weird, you want to rename the package name to cooln64 and add advertisements?

**Comment by loganmc10** [comment]
I'm pretty sure he is just creating yet another Play Store clone with ads and he hasn't quite figured out how GitHub works yet.

**Comment by fzurita** [comment]
Figured as much

**Comment by fzurita** [comment]
He leaked his API key as well

**Comment by xperia64** [comment]
If you noticed, they've also recently renamed and changed all the info and profile pictures on their accounts. If I had to take a guess I'd say this might've been part of a business school project presentation or something.
Or they just don't know how GitHub works and they were trying to upload their changes to their own account(s).

**Comment by fzurita** [comment]
Yeah, I can still see their old name.

**Pull request closed without merging**
