### PR TITLE
front: Use AppCompat selectors in the Gallery

### PR DESCRIPTION
**Pull request by easyaspi314**
@fzurita Test first. This *should* remove the orange for good.

### CODE REVIEW

**Comment by fzurita** [comment]
Hmmm, which orange are you talking about?

**Comment by easyaspi314** [comment]
https://youtu.be/lBtkYAGepEk

Sorry about the black screen ending, my phone + YouTube derped.

**Comment by fzurita** [comment]
Not exactly compiling:
```
gallery_item_adapter.xml:2: error: Error: No resource found that matches the given name (at 'background' with value '?attr/selectedItemBackground').
```

**Comment by easyaspi314** [comment]
Derp. Fixed.

**Comment by fzurita** [comment]
Ok, works now. It's merged.

**Pull request closed without merging**
