### PR TITLE
Crash on exit fix

### PR DESCRIPTION
**Pull request by fzurita**
Fixes crash on exit issue.

### CODE REVIEW

**Comment by fzurita** [comment]
Here is the logcat with the log printed out after catching the exception:
https://drive.google.com/file/d/0B57Ioy26LWegSUtYa2Vxc1hwMjQ/view?usp=sharing

Here is the logcat without catching the exception:
https://drive.google.com/file/d/0B57Ioy26LWegSURvOVg0S05sMlk/view?usp=sharing

**Comment by Gillou68310** [comment]
Thanks but actually I'll need a complete lifecycle log in order to debug this :-p
https://www.dropbox.com/s/pa5shnz79fq8hmq/lifecycle.txt?dl=0

**Comment by fzurita** [comment]
Here you go:

https://drive.google.com/file/d/0B57Ioy26LWegYnBHNzBsdEpZV1k/view?usp=sharing

**Comment by Gillou68310** [comment]
Thanks I'll check this

**Comment by Gillou68310** [comment]
Hum is this happening with all video plugins or just GlideN64? I don't understand why flipBuffers is called after emulation stops.

**Comment by fzurita** [comment]
It may just be GLideN64

**Comment by Gillou68310** [comment]
Could you check please :-p

**Comment by fzurita** [comment]
Yep, I will.

**Comment by Gillou68310** [comment]
@fzurita could you check if this fix the issue for you?
https://github.com/mupen64plus-ae/mupen64plus-ae/commit/460680e0b32279a0b655f9e28665775313c60b77

**Comment by fzurita** [comment]
Sure, I'll try it when I get a chance. Last couple of days have been really busy for me.

**Comment by Gillou68310** [comment]
Sure no problem ;-)

**Pull request merged**
