### PR TITLE
Tv mode improvements

### PR DESCRIPTION
**Pull request by fzurita**
App is fully navigational in TV mode when using a controller (except for controller overlay activity).

### CODE REVIEW

**Comment by xperia64** [comment]
The multiple button -> single N64 is useful due to the awkward layout of the N64 controller in general. I like having both RB and RT mapped to R, and I like mapping both the right joystick and some of the face buttons to the C buttons for ease of access in certain games.

**Comment by fzurita** [comment]
Ok, I will revert that one change.

**Comment by fzurita** [comment]
Another note, right now there is no easy way to unmap a single button while using only a controller. The only two options right now are to unmap all (which wasn't even accessible before these set of changes from a controller), or assign the existing key to another button.

I'm thinking about adding a hold function when selecting buttons in the ControllerProfileActivity for TV mode. Holding a key for 2 seconds will unmap all controller assignments to that button.

**Comment by littleguy77** [comment]
@fzurita Skimming the commits, this sounds like a well-done and much-needed commit.  Many thanks :+1: 

I'd like to give this a full review will all my controllers and devices just to make sure all the corner cases are handled.  @xperia64 and @Gillou68310 feel free to merge if you don't hear back from me in a couple days.

**Comment by fzurita** [comment]
Another change that still needs to be done is have all the built-in profiles have the menu key assigned by default. It's not obvious to a new user that they have to assign that key to access that menu. Without that key assigned, it's impossible to even exit the game.

**Comment by fzurita** [comment]
I think it should be in the pull request since I had to make additional change to de-conflict the merge. The odd thing is that so many additional files were part of the merge commit. I would had thought that only the files that I had to de-conflict would had shown up.

**Comment by Gillou68310** [comment]
Ok I cherry picked your commits, cleaning up a few things during the process ;-)
@littleguy77 put a lot of effort keeping a clean history and I don't want to break is work.
https://github.com/mupen64plus-ae/mupen64plus-ae/commits/tv_mode_improvements

**Comment by Gillou68310** [comment]
BTW don't hesitate to double check my cherry picks!

**Comment by fzurita** [comment]
I was going to do the rebase last night. I think I understand how it works. You beat me to it though.

**Comment by Gillou68310** [comment]
I noticed that the covert art don't go up anymore when navigating down the game sidebar. This makes the navigation a bit harder.

**Comment by fzurita** [comment]
Ok, I looked through the branch you made. Everything looks good, only thing missing is the merge conflicts.

**Comment by fzurita** [comment]
Oh, wait, never mind, It seems like you resolved them.

**Comment by Gillou68310** [comment]
Yeah I removed the merge conflicts from the log after resolving them

**Comment by fzurita** [comment]
Also, I see your e-mail about the cover art? I haven't run into that yet. It seems to behave the same way as before this set of commits. Did you do anything special to replicate it?

**Comment by littleguy77** [comment]
@Gillou68310 Nice job :+1:  I tried the rebase myself and came up with exactly the same result :)

I'll give this a test this morning before I head out to work.

**Comment by Gillou68310** [comment]
Also if I hit the back button while the game sidebar is visible, the game exit without showing up the prompt message. Not sure this was happening before.

**Comment by Gillou68310** [comment]
@littleguy77 ;-)

**Comment by Gillou68310** [comment]
@fzurita about the covert art, maybe your screen is big enough to show the whole sidebar, you won't notice the difference in this case.

**Comment by littleguy77** [comment]
@fzurita As a concrete example of interactive rebase, here's the process I used.  First switch the the `tv_mode_improvements` branch, then issue this command through the git terminal or a GUI:
```
git rebase -i master
```

You will then get a list of commits.  If using the terminal or a GUI like GitExtensions, a text editor will pop up containing the following:
```
pick 446b53a Refactored ControllerProfileActivity
pick 6561733 Save ControllerProfileActivity ListView position
pick 54181e9 Save selected position after binding a key.
pick 7d60397 Mapping a key now automatically increments the selected button.
pick dfa860d Profile menus are now navigational using a controller
pick bc926ab Can no longer map more than one controller key to N64 key
pick 59c5fe7 Mapping buttons using touch in TV mode will no longer reset the scroll position.
pick 7ca8675 ControllerProfileActivity is now navigational using a controller
pick 471dd01 Missed commit.
pick 4146476 Made the GameSidebar view internally use the MenuLustView.
pick 5a4d7ed Re-added game speed functionality.
pick d825706 Added slot save selection dialog.
pick 3a46d5c Completed save slot in game cinfig.
pick 35b086a Completed replacement for Pak selection during in-game.
pick e0060f1 Don't allow navigating out of the side bar when using a controller. Only back key will exit the side bar.
pick bc79c3b Re-allow mapping more than one controller key to the same N64 button.
```

Note that git intelligently removes the merge commit from this list since the act of rebasing alone accomplishes the same thing as the merge commit.  Now edit the text as follows:

```
pick 446b53a Refactored ControllerProfileActivity
pick 6561733 Save ControllerProfileActivity ListView position
pick 54181e9 Save selected position after binding a key.
pick 7d60397 Mapping a key now automatically increments the selected button.
pick dfa860d Profile menus are now navigational using a controller
pick 59c5fe7 Mapping buttons using touch in TV mode will no longer reset the scroll position.
pick 7ca8675 ControllerProfileActivity is now navigational using a controller
f 471dd01 Missed commit.
pick 4146476 Made the GameSidebar view internally use the MenuLustView.
pick 5a4d7ed Re-added game speed functionality.
pick d825706 Added slot save selection dialog.
pick 3a46d5c Completed save slot in game cinfig.
pick 35b086a Completed replacement for Pak selection during in-game.
pick e0060f1 Don't allow navigating out of the side bar when using a controller. Only back key will exit the side bar.
```

Note the following changes:
 - Remove the line `pick bc926ab Can no longer map more than one controller key to N64 key`
 - Remove the line `pick bc79c3b Re-allow mapping more than one controller key to the same N64 button.`
 - Change the line `pick 471dd01 Missed commit.` to `f 471dd01 Missed commit.`

The first two changes remove an unneeded modification from the history.  The third change tells git to simply squash the commit into the previous one without changing the previous one's commit message.

That was the easy part.  The trickier part comes when you try to resolve the conflicts as git starts rebasing.  This is where you have to *really understand* your three-way merge tools (whichever you happen to choose), and what "ours" and "theirs" refers to.  During a rebase "ours" refers to changes on `master` since the original branch point, while "theirs" refers to changes on `tv_mode_enhancements`.  This is utterly confusing at first.  The way to remember this is that during a rebase, git first switches to `master` (which is why it is "ours") then effectively cherry-picks the changes from the original `tv_mode_enhancements` branch (which is why it is "theirs").

Learning how to rebase is not for the faint of heart, but once you learn how to do it, and do it well, you'll never look back.  At my day job I use it many times a day, on my own local branches as well as colleagues' pull requests.

Hope this helps...

**Comment by Gillou68310** [comment]
Hum the onKey method isn't called in GameLifecycleHandler when hitting back key while game sidebar is open.

**Comment by fzurita** [comment]
@Gillou68310 yep, I can confirm both regressions. The Game art isn't going away in this branch and the onKey isn't getting called when in the GameSideBar view.

I think both are fixable things. Thanks for noticing. Should we get this committed first and then making fixes or should we make the fixes within this pull request?

**Comment by Gillou68310** [comment]
I suggest fixing both issues before merging the pull request.

**Comment by fzurita** [comment]
Ok, I'll checkout the branch you made and go from there.

**Comment by Gillou68310** [comment]
Perfect ;-)

**Comment by littleguy77** [comment]
Thanks guys, agreed.  As a general rule, I think it's better not to push known regressions into master from a branch.  IMO the exception to this rule is if the branch fixes a critical defect and the regression is relatively minor and can be documented well before the merge...  I personally find it very fatiguing to get laundry lists of new bug reports from testers.  Testers tend have a lower tolerance for regressions than other types of defects, and thus are more vocal about them.

**Comment by fzurita** [comment]
Ok, I'll get to it tonight after putting my kids to bed (about 13 hours from now). @Gillou68310 I made two other pull requests by the way. They are fairly small compared to this one and fix some annoyances that retroben has been seeing.

**Comment by Gillou68310** [comment]
Ok I'll take a look at them

**Comment by littleguy77** [comment]
I think everything up through `ControllerProfileActivity is now navigational using a controller` (on the rebased branch) can and should be merged now.  Those are critical usability fixes and do not affect in-game behavior nor create regressions (in any of my testing at least).

The remaining commits relate to the in-game sidebar and can be broken out into a separate pull request, and merged after the regressions are fixed.

**Comment by littleguy77** [comment]
In any case these are great updates, long overdue :)

**Comment by littleguy77** [comment]
Minor regression, all four players' controller paks are listed even for games that don't support four players.  e.g. previously only Player 1's controller pak would be listed in Mario 64.

**Comment by fzurita** [comment]
Yeah, I thought about that, but since the Pak settings are a global preference and not a game preference, it didn't make sense to limit it to what the game supports. Although, it's not big deal to remove the option. I'll add that to my regression list.

**Comment by fzurita** [comment]
Although, why are the Pak settings a global preference and not a game specific preference?

**Comment by littleguy77** [comment]
> Although, why are the Pak settings a global preference and not a game specific preference?

Good question ;)  I can't remember the answer but it might simply be that I ran out of time :P

Even if they remain global, removing the irrelevant ones helps with clutter and reduces confusion.

**Comment by littleguy77** [comment]
Not a regression, but in the future we might consider always pausing the emulator when the sidebar is open, not just for certain actions within.  If Mario happens to be moving when the sidebar opens, he continues to move until I exit the sidebar.

**Comment by littleguy77** [comment]
The new Pak selection dialog is a nice improvement.  Though the use of spinners for text is a bit unorthodox for Android UI design.  The usual approach would be to use a listview based dialog, like done for file selection.  Copying and tweaking the `Prompt.promptFile` implementation would probably suffice.  That also might eliminate the need to create new enums and such for the Pak values.

**Comment by fzurita** [comment]
Sure, I could migrate the Pak selection to use the a view similar to ```Prompt.promptFile```. I'll add it to the list :)

**Comment by fzurita** [comment]
I'm almost there. The cover art issue is giving me some grief.

Everything minus that issue fixed is right here:
https://github.com/fzurita/mupen64plus-ae/tree/tv_mode_improvements_part2


For the cover art issue, i'm thinking of doing this:
http://developer.android.com/reference/android/widget/ListView.html#addHeaderView%28android.view.View%29

**Comment by Gillou68310** [comment]
Why did you merge these commits into the branch?
https://github.com/fzurita/mupen64plus-ae/commit/1657a7f07be7118d9db55b2c11a1e589e28aa385
https://github.com/fzurita/mupen64plus-ae/commit/66231cba33e1621a1027ab54cf1b347bf54b652a
https://github.com/fzurita/mupen64plus-ae/commit/ad6bc68f29bf23ab4a2f27c7a61a92e4afd1569b
https://github.com/fzurita/mupen64plus-ae/commit/42feb321dded4fd1d91c0f3c21d4433061555225
I already merged them into master!

**Comment by fzurita** [comment]
hmmmm.... I took master, created a new branch out of it called tv_mode_improvements_part_2, then I did a rebase againt the mupen64plus-ae/tv_mode_improvements branch.  Maybe that wasn't the right steps to take.

**Comment by Gillou68310** [comment]
Lol actually you should have done a checkout of mupen64plus-ae/tv_mode_improvements to your local repo, rebase the branch against master and commit your changes. I know git is hard to understand at first but once you understand the basics it's a very powerfull tool ;-)

**Comment by fzurita** [comment]
I'll do what you just said into a new branch then cherry pick my commits so far into it.

**Comment by fzurita** [comment]
ok, I think I did it correctly this time around.... new branch:

https://github.com/fzurita/mupen64plus-ae/commits/tv_mode_improvements_duh

**Comment by fzurita** [comment]
I'll try to get the cover art issue fixed by tonight, I ran out of time last night. So hopefully we can get this all merged by tonight or tomorrow.

**Comment by fzurita** [comment]
Ok, cover art issue is fixed. I made a new pull request with all regressions fixed: https://github.com/mupen64plus-ae/mupen64plus-ae/pull/497

**Pull request closed without merging**
