### PR TITLE
Sles audio deadlock

### PR DESCRIPTION
**Pull request by fzurita**
Hopefully fix the SLES audio deadlock that sometimes happens when starting a game.

See this issue:

https://github.com/mupen64plus-ae/mupen64plus-ae/issues/514

### CODE REVIEW

**Comment by fzurita** [comment]
@Gillou68310 I went ahead and made the changes you requested. I'm going to go ahead and merge this pull request along with the minimum API level one.

**Comment by Gillou68310** [comment]
A bit late but ok by my side ;-)

**Comment by fzurita** [comment]
Now I'm hoping Paul fixes the auto build script soon. He was making progress, I may have to ping him again to see where he is at.

**Comment by paulscode** [comment]
Auto-build is failing with:

BUILD FAILED
/home/paul/bin/android-sdk/tools/ant/build.xml:597: The following error occurred while executing this line:
/home/paul/bin/android-sdk/tools/ant/build.xml:649: The following error occurred while executing this line:
/home/paul/bin/android-sdk/tools/ant/build.xml:655: /home/paul/auto-build/mupen64plus-ae/libs/extras/android/support/v7/recyclerview/src does not exist.

**Comment by fzurita** [comment]
We are getting closer. That's an easy fix.

**Comment by fzurita** [comment]
The src directory refuses to exist without a file in it in git... Strange

**Comment by fzurita** [comment]
I'll just keep an empty file in it.

**Comment by fzurita** [comment]
@paulscode Can you try again?

**Comment by paulscode** [comment]
It built.  Testing now.

**Comment by paulscode** [comment]
It is working well.  Thanks!

**Comment by fzurita** [comment]
@paulscode thanks for getting it to work :)

**Comment by Gillou68310** [comment]
I just tested this and unfortunately dead locks still happens :-(

**Comment by fzurita** [comment]
Ok, that's unfortunate. I'll leave the code as is since I think it's more correct behavior. Do you have a way of making the dead lock happen more often?

**Comment by Gillou68310** [comment]
I noticed that pausing/resuming (open/close sidebar) a game often usually helps making a dead lock.

**Comment by fzurita** [comment]
Ok, I see what you mean. I know what the solution should be. Unfortunately GLideN64 forces the aspect ratio to 4:3, so it can't work with that.

**Comment by fzurita** [comment]
So I assigned a controller key to pause/resume. I'm spamming it like crazy, but I can't get the deadlock to happen.

Also, while trying to trigger this, I noticed that if I hit the back button during gameplay to bring up the confirmation dialog to exit the game. If one hits the back key to exit the dialog, the game doesn't un-pause.

**Pull request merged**
