### PR TITLE
Add Github Workflow and remove Travis CI

### PR DESCRIPTION
**Pull request by bladeoner**
This PR changes the following things:
- Add a Github Workflow which can be found under Actions: https://github.com/mupen64plus-ae/mupen64plus-ae/actions
- Removes the Travis CI.
- Add a Badge in the README.md so you can see if a build fails or not on the front page.
The Badge will be available after the first succesful build.
- Add the buildToolsVersion for making the Github Workflow work.

The PR triggered a build on my Github page where you can see it will succeed:
https://github.com/bladeoner/mupen64plus-ae/actions

On the following page you can see how the README.md will look, only the badge will not be showing because it's directed to your Github page and a build will only be triggered after you commit this PR:
https://github.com/bladeoner/mupen64plus-ae/tree/workflow

The next thing I will be working on after this PR is added is to upload the Artifacts, then we will have Nightly Builds.

### CODE REVIEW

**Comment by bladeoner** [comment]
The PR triggered a build on my Github page where you can see it will succeed: 
https://github.com/bladeoner/mupen64plus-ae/actions

**Comment by bladeoner** [comment]
Build is still running on my page, had to adjust something.

**Comment by bladeoner** [comment]
The build completed successfully.

**Comment by fzurita** [comment]
Well, this looks interesting. We can give it a shot. If GitHub can provide the same functionality as Travis, I would rather have that.

**Pull request merged**
