### PR TITLE
Fix incorrect gallery art

### PR DESCRIPTION
**Pull request by fzurita**
Fixed issue where the incorrect gallery art is shown momentarily if scrolling very fast.

### CODE REVIEW

**Comment by Gillou68310** [comment]
> Fixed issue where the incorrect gallery art is shown momentarily if scrolling very fast.

This is still happening on my device.

**Comment by fzurita** [comment]
Hmmm, not good, I may have to try this on other devices. It worked OK on the onr device I tested

**Comment by fzurita** [comment]
Well, I think I actually know what the problem is. The way I'm cancelling the ASync task is not reliable enough. I can make additional commits to fix it. It just requires one additional change in the task it self so that it is aware that it was cancelled.

**Comment by fzurita** [comment]
Ok, I made a new commit. Please try again when you get a chance.

**Comment by Gillou68310** [comment]
Nope still happening.

**Comment by fzurita** [comment]
Hmmm, I wonder what's different in your device.

**Comment by fzurita** [comment]
What version of Android do you have?

**Comment by Gillou68310** [comment]
4.4.2

**Comment by fzurita** [comment]
I'm testing on devices with 5.1. I actually have a device with that version of android, I'll see if I can reproduce it there.

**Comment by Gillou68310** [comment]
Ok ;-)

**Comment by fzurita** [comment]
So, I just checked this out in my 4.4 device and it seems to be working correctly there. Just to make sure, the default covert art is supposed to show up while the real cover art is loading.

Before this fix, the cover art for another game could show while the real cover art was loading. Is that what you are seeing in your device with this fix?

**Comment by Gillou68310** [comment]
Oh sorry for the misunderstanding I thought the default covert was the incorrect gallery art.

**Pull request merged**
