### PR TITLE
Support Google Cardboard VR

### PR DESCRIPTION
**Pull request by justinmichaud**
screenshot_20170817-214125

I just wanted to know, if I would clean this up and put it behind a config option, would you be willing to merge it? It is a big mess right now, but excepting a few small graphical glitches, it seems to work. At the same time, I could understand not wanting to take on the additional maintenance burden. 

If you want to try it out, use the gladen64 plugin + widescreen fix.

Thanks for making such a cool emulator!

### CODE REVIEW

**Comment by fzurita** [comment]
@justinmichaud This is interesting work. I have not looked carefully through all of your commits, but I see that you made changes to Rice and GLideN64. This project is meant to be mostly a front end to the cores and plugins so all changes to all the C/C++ code should be done in the appropriate upstream projects. In this case, it would be these two projects:
https://github.com/mupen64plus/mupen64plus-video-rice
https://github.com/gonetz/GLideN64

The maintainers of these two projects are very open to taking in pull requests as long they are fairly clean. In this case, I can see that you added a lot of Android specific stuff in the VR.cpp classes. If you are able to wrap this code around a configuration parameter as well as compiler macros so that this code is only compiled under Android, I think the upstream projects will take the code. The code should also be free of any major bugs. I can help you with all this if you want.

I think something like this is definitely worth incorporating into this app since a lot of users have been asking for a Google cardboard option for a while. I think you should definitely keep working on this until it's completely ready. I will give it a try probably tomorrow when I have the time. Also, feel free to keep making updates to this pull request as you work on this.

**Comment by justinmichaud** [comment]
I cleaned up the code a bit and added a config option. Also, the android code is behind an #ifdef. Only GlideN64 is affected. 

I can submit a PR for GlideN64, but I am not sure how to build/test it on Android outside of this project. For now, I will try to build it on Windows to make sure that the #ifdef is working correctly.

**Comment by fzurita** [comment]
Building GLideN64 in Windows is a real pain. I've been short on time lately, but I can try building it if you get stuck once I get the time.

**Comment by justinmichaud** [comment]
For some reason, I had Windows on the mind. I meant to say Linux. I got it to build, but I can't get the unmodified master branch of gliden64 to work:

```
[justin@localhost ~]$ mupen64plus --gfx mupen64plus-video-GLideN64.so mupen64plus-bundle-linux64-2.5/m64p_test_rom.v64 
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Goodname: Mupen64Plus Demo by Marshallh (GPL)
Core: Name: Mupen64Plus         
Core: MD5: DBF04773EC2B8ADF8A94DB7E3E461138
Core: CRC: DDBA4DE5 B107004A
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 1048576 bytes (or 1 Mb or 8 Megabits)
Core: Version: 1444
Core: Manufacturer: 0
Core: Country: Demo
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'GLideN64' v2.0.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Forcing default keyboard configuration
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input Warning: Couldn't open rumble support for joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
(II) Setting video mode 640x480...
Core: Setting video mode: 640x480
Core Error: SDL_SetVideoMode failed: Could not create GL context: GLXBadFBConfig
Segmentation fault (core dumped)
```

My opengl version should be high enough though:
```
$ glxinfo | grep -i opengl 
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.1.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.1.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 17.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

Any ideas? Thanks for the help!

**Comment by loganmc10** [comment]
Can you post the contents of gliden64.log? It should be in ~/.local/share/mupen64plus

I don't know why glxinfo says:
```
OpenGL version string: 3.0 Mesa 17.1.5
```

But earlier it seems to say that your card supports 4.5, GLideN64 requires at least 3.3

**Comment by justinmichaud** [comment]
I was concerned about that line as well. It seems to be capped at 3.0 on many cards though.

Here is the log:
```
[gles2GlideN64]: Error setting videomode 640x480
[gles2GlideN64]: Error setting videomode 640x480
[gles2GlideN64]: Error setting videomode 640x480
```

Why would it be using gles? I haven't made any modifications to the code yet.

**Comment by justinmichaud** [comment]
I compiled both projects from source

**Comment by loganmc10** [comment]
It's not actually using gles, that's just a mislabeled error message.

You can try a binary build here to check if it's a compilation issue:
https://m64p.github.io

If you try that, I would try ```./mupen64plus``` and ```./mupen64plus-gui```, which is a Qt frontend that creates the GL context in a different way, so you might have more success. If that doesn't work, then I'm not quite sure what the issue might be.

**Comment by loganmc10** [comment]
You can try and get more debug info by setting some environment variable:

https://www.mesa3d.org/envvars.html

Particularly LIBGL_DEBUG and MESA_DEBUG. Something in there might give a clue as to what the issue is

**Comment by justinmichaud** [comment]
@loganmc10 Thanks for the help! m64p solved my problems, and was so incredibly easy to set up! 

I made a PR to GLiden64, and separated out the java changes to the PR above.

Thanks!

**Pull request closed without merging**
