### PR TITLE
add missing translations

### PR DESCRIPTION
**Pull request by williansti**
added small translations of items that were missing

### CODE REVIEW

**Comment by fzurita** [comment]
Hello, thanks for the contribution. I don't believe that translation requests are usually accepted as pull requests. If you want to contribute a translation, please go here:

https://www.transifex.com/paulscode/mupen64plus-ae/

We periodically pull updated translations from there. Although, it has been a while now. Thanks :)

**Comment by williansti** [comment]
thank you for guidance, i noted in transifex that Portuguese pt-br brazil is 100% translated, what is false for I see words in english, it is missing the strings I added here, already in Portuguese pt-pt portugal they are untranslated there.

**Comment by fzurita** [comment]
I'm going to include your pull request. I'm not exactly sure how to update what is in transifex. @littleguy77 @Gillou68310 @paulscode any idea?

**Comment by fzurita** [comment]
Ok, your change is in. See here:

https://github.com/mupen64plus-ae/mupen64plus-ae/commit/876a3c8afae92b748fd7cebd8c58403cde5577a6

**Comment by williansti** [comment]
@fzurita I did send the translation of two languages, PT-BR - Brazil and PT-PT Portugal in transifex, despite the system consists i sent, to re-download the files 100% translations do not appear, i do not know if you have a process of review and approval there, i did it 4 days ago looks a
transl
nnex.

**Comment by fzurita** [comment]
Ok, thanks, I'll look into it.

**Comment by fzurita** [comment]
I'm going to go ahead and merge this since I have not been able to get anything from transifex for a long time.

**Pull request closed without merging**
