### PR TITLE
Update SDL2 to 2.0.8

### PR DESCRIPTION
**Pull request by loganmc10**
Contains debug and release shared libraries, and updated headers. I removed all the other unneeded source code.

To build the shared libraries I simply downloaded the source and ran ```ndk-build NDK_DEBUG=0/1```, I didn't have to make any modifications.

I did come across one crash:
```
********** Crash dump: **********
Build fingerprint: 'essential/mata/mata:8.1.0/OPM1.180104.092/224:user/release-keys'
pid: 17358, tid: 17390, name: ServiceStartArg  >>> paulscode.android.mupen64plusae.GameActivity <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #00 pc 00026dfe  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libSDL2.so (Android_JNI_GetEnv+25): Routine Android_JNI_GetEnv at jni/src/core/android/SDL_android.c:969
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #01 pc 000285cd  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libSDL2.so (Android_JNI_PollInputDevices+4): Routine Android_JNI_PollInputDevices at jni/src/core/android/SDL_android.c:1839
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #02 pc 0003cfb1  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libSDL2.so (SDL_SYS_JoystickDetect+36): Routine SDL_SYS_JoystickDetect at jni/src/joystick/android/SDL_sysjoystick.c:496
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #03 pc 0003c397  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libSDL2.so (SDL_JoystickUpdate_REAL+226): Routine SDL_JoystickUpdate_REAL at jni/src/joystick/SDL_joystick.c:896
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #04 pc 00034a1b  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libSDL2.so (SDL_PumpEvents_REAL+34): Routine SDL_PumpEvents_REAL at jni/src/events/SDL_events.c:650
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #05 pc 00010b24  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libmupen64plus-core.so: Routine main_check_inputs at mupen64plus-ae/mupen64plus-core/./upstream/src/main/main.c:216
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #06 pc 000b66d4  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libmupen64plus-core.so: Routine vi_vertical_interrupt_event at mupen64plus-ae/mupen64plus-core/./upstream/src\device/rcp/vi/vi_controller.c:156
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #07 pc 000401d0  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libmupen64plus-core.so: Routine call_interrupt_handler at mupen64plus-ae/mupen64plus-core/./upstream/src/device/r4300/interrupt.c:499
Stack frame 03-22 13:54:55.417 17405-17405/? A/DEBUG:     #08 pc 000b7af8  /data/app/org.mupen64plusae.v3.alpha-UKDRa2KU-kKbRdv5yRKDTg==/lib/arm/libmupen64plus-core.so: Routine .E1 at linkage_arm.S:?
```

Commenting out SDL_PumpEvents() in mupen64plus-core fixes the issue. I was planning on submitting a PR to mupen64plus-core to surround that call by ```#ifndef ANDROID``` if you think that is alright. Since mupen64plus-ae doesn't use SDL for input it shouldn't make any difference.

### CODE REVIEW

**Comment by fzurita** [comment]
Thanks. For the crash I think we should do the correct fix in Android which is to correct whatever is happening in SDL_android.c:969. I suspect it's probably just an unimplemented function.

**Comment by fzurita** [comment]
It looks like we just have to implement these:

```
    midPollInputDevices = (*mEnv)->GetStaticMethodID(mEnv, mControllerManagerClass,
                                "pollInputDevices", "()V");
    midPollHapticDevices = (*mEnv)->GetStaticMethodID(mEnv, mControllerManagerClass,
                                "pollHapticDevices", "()V");
    midHapticRun = (*mEnv)->GetStaticMethodID(mEnv, mControllerManagerClass,
                                "hapticRun", "(II)V");
```

They could just be blank implementations.

**Comment by fzurita** [comment]
It looks like there is an example here:

https://github.com/spurious/SDL-mirror/blob/f0be85b8b3bb1daa9849e37f9298e06aa619d574/android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java

**Comment by fzurita** [comment]
And one last thing, can you submit an update here with the latest SDL2?

https://github.com/mupen64plus-ae/mupen64plus-ae-deps

**Comment by loganmc10** [comment]
I'm not too familiar with how it's all supposed to work, but it looks like the crash is happening here:

https://github.com/spurious/SDL-mirror/blob/master/src/core/android/SDL_android.c#L976

That is line 969 in the 2.0.8 sources, I'm not sure why it crashes, or if it could be related to those functions.

Really, the SDL_PumpEvents call should be in the input plugin. I'm not sure why it's in the core, that is kind of assuming that the input will be handled by SDL, which goes against the purpose of having an input plugin. We could potentially create all this dummy stuff to make it work, but I don't know if that is the right approach

**Comment by fzurita** [comment]
Ok, I'll try to figure out why once I get home. I'm reluctant to update the core for a crash that is due to an issue in the Android implementation of SDL. I think we are just missing something simple. And you are right, not sure why the core is trying to get controller status directly without using the input plugin.

**Comment by loganmc10** [comment]
Ok, and I didn't realize you had a dependencies repo. You can build the libraries using that and close this PR once this get sorted out. Besides this one issue with SDL_PumpEvents, it was just "plug and play", no modifications to any source code, so it should be easy to update.

The SDL2 library being used is pretty old so I figured it was time for an update.

**Comment by fzurita** [comment]
Yep, it definitely makes sense. It didn't seem to be broken, so why fix it :).

**Comment by fzurita** [comment]
Ok, for a proper solution without a crash, I would have to build SDL2 as part of the standard build instead of in the mupen64plus-ae-deps project. I would then have to include all the java code inside of SDL.

I would rather not do all that and simply wait for the core to update to not use input related stuff outside the input plugin. I'll keep this open until then.

**Comment by fzurita** [comment]
Why did you close it?

**Comment by loganmc10** [comment]
Oh whoops, I was going through stale branches and I thought this was one.

Should I re-open? I'm still waiting for https://github.com/mupen64plus/mupen64plus-core/pull/550 to be merged, but wouldn't the proper workflow be to update it from the ae-deps project? Once that PR is merged, SDL can be updated without any modifications at all, so it should be quite straight forward

**Comment by fzurita** [comment]
Yep, true.

**Pull request closed without merging**
