### PR TITLE
Profile improvements

### PR DESCRIPTION
**Pull request by fzurita**
Fixed issue that caused the wrong profile to be selected if a custom profile is currently default.

Also, added a "Current Default" profile that will always select the current default

Made this profile the default profile.

### CODE REVIEW

**Comment by Gillou68310** [comment]
"Current Default" profile is missing for Controller profile

**Comment by fzurita** [comment]
You have to select a default profile first.

**Comment by fzurita** [comment]
Although, I could probably allow it without a default profile selected.

**Comment by Gillou68310** [comment]
I guess (Disabled) should be the default profile, right now there is a %1$s instead of the default profile

**Comment by fzurita** [comment]
Where do you see the " %1$s" text?

**Comment by Gillou68310** [comment]
In game preference activity, under Controler profile.

**Comment by fzurita** [comment]
Hmmm... not good, I didn't see it in my testing. I'll check it out tonight.

**Comment by Gillou68310** [comment]
Ok

**Comment by Gillou68310** [comment]
Any news about this, this is still an issue by my side. Just uninstalling - re-installing you should be able to reproduce it

**Comment by fzurita** [comment]
I didn't really have much time last night, I'll probabky get to it tonight.

**Comment by Gillou68310** [comment]
Ok no problem just wanted to be sure you didn't forget about it ;-)

**Comment by fzurita** [comment]
Nope, I haven't, it's in my TODO list.

**Comment by fzurita** [comment]
Just to clarify, it only happens in the Controller profiles?

**Comment by fzurita** [comment]
I think to fix it, I'm going to add a default profile of "None" to the controller profiles. Do we have some code somewhere that selects the correct controller profile based on the current controller? I will have to only set the default to none if no controller is detected if that's the case.

**Comment by Gillou68310** [comment]
> Just to clarify, it only happens in the Controller profile selection?

Yep

**Comment by littleguy77** [comment]
Yeah I bet it happens because there is no global default controller profile.

I think the default for the Controller Profile value in each game should be "Disabled" rather than "Current Default" (and adding a "None" profile to the built-ins).  Trying to auto-detect the plugged controller is a nasty rabbit hole that is best to avoid.  Too many variations between controllers, Android devices, and Android versions to do it well.

**Comment by fzurita** [comment]
I think I will keep the "Current Default" option. The "Current Default" option should correctly point to the "None" controller profile.

**Comment by fzurita** [comment]
How about a compromise. How about we keep the "Current Default" option for controllers and make "Disabled" the default rather than a "none" built in profile?

**Comment by littleguy77** [comment]
Sounds good to me.  That's basically what I was saying.  I like the Current Default option.  I just thought a None profile was a little hackish.

**Comment by fzurita** [comment]
Gotcha

**Comment by littleguy77** [comment]
Minor note, you might consider calling it Global Default rather than Current Default..  Maybe a little more clear?  Just a thought.

**Comment by fzurita** [comment]
Not a bad idea, I'll do that as well.

**Pull request merged**
