### PR TITLE
Update Gradle

### PR DESCRIPTION
**Pull request by bladeoner**
This doesn't resolve issue #997, just an update.

### CODE REVIEW

**Comment by bladeoner** [comment]
I need to rebase it before it can be added

**Comment by bladeoner** [comment]
Rebase has been done.

**Comment by fzurita** [comment]
I usually stick to the version that Android studio recommends since I know it has been tested well with it. Does going with this later version bring any advantages? If not, I would rather wait until an Android studio update recommends that specific version.

**Comment by bladeoner** [comment]
It doesn't bring any advantages directly for us, but security wise it is patched for the log4j security bug that was what interested me to keep things safe.

**Comment by fzurita** [comment]
I see, I would rather wait since as far as I know the log4j security bug doesn't directly affect the app. Also, you would think that Android studio would update to the later version on their own if that security vulnerability affected Android studio.

**Comment by bladeoner** [comment]
Yes, that's true I will close this PR.

**Pull request closed without merging**
