### PR TITLE
[WIP/RFC] New gallery part 1

### PR DESCRIPTION
**Pull request by littleguy77**
@BonzaiThePenguin 

Thanks once again for breathing new life into the main UI !!!

I'm posting this set of commits as a PR so you can take one last peek before I merge (in case I messed anything up or you had more you wish to add).  In short, I rebased and squashed about half of your latest commits regarding the new gallery activity.  These commits basically reimplement the current design using the appcompat library and Material Design patterns.  These are the "machinery" commits that change the guts of the underlying UI mechanisms:
 - add modern search bar at top of gallery
 - use memory-efficient grid implementation
 - polish the sizing/spacing aesthetics of the grid items
 - add game-specific context menu to each grid item
 - allow user to jump straight from gallery to game activity (skip play menu activity)
 - add "recently played" section to gallery
 - move most action bar menu items to left-side navigation drawer

These commits do not change the menu hierarchy, string resources, play menu activity, or ROM search/refresh/extract mechanics.  That's for part 2.

### CODE REVIEW

**Comment by BonzaiThePenguin** [comment]
I'll check it out in a bit! I might make another branch named Experimental so I can make a clean break from the stuff related to the new gallery design. Yesterday I worked on figuring out how to switch PreferenceActivity and ListActivity over to the material theme with a Toolbar without having to resort to nasty version-specific hacks (and succeeded!), and finally started thinking about how to clean up some of the new components I added (like GalleryView.java is just a stub right now, should eventually take care of more logic, and FAB and the game sidebar should probably be split off into their own classes).

**Comment by littleguy77** [comment]
>I might make another branch named Experimental so I can make a clean break from the stuff related to the new gallery design.

Sounds great!  I'd recommend using a more specific name though ;)  (So that it's clear and also because the branch name ends up in the title of the [auto-builds](http://www.paulscode.com/source/Mupen64Plus-AE/AutoBuilds/).

**Comment by littleguy77** [comment]
Merged via other means.

**Comment by littleguy77** [comment]
Merged manually due to my GitHub incompetence
https://github.com/mupen64plus-ae/mupen64plus-ae/commit/d63c42efa6d4174ca985aa40e16676eabe1da107

**Comment by BonzaiThePenguin** [comment]
Oh, neato! I better get on cleaning up the loose ends in the sidebar.

**Comment by BonzaiThePenguin** [comment]
Oh never mind, I thought you merged `New-Gallery-UI`. Did you want me to break the new features into separate commits? It'd probably be a lot faster for me since I've done it all before. Wouldn't need to wade through the commits trying to make sense of how they all tie together.

**Comment by littleguy77** [comment]
Absolutely, that would be by far the best path.  I'll post some more on #420

**Pull request closed without merging**
