### PR TITLE
git subrepo clone --branch=master --force https://github.com/gonetz/G…

### PR DESCRIPTION
**Pull request by bladeoner**
…LideN64.git mupen64plus-video-gliden64/upstream

subrepo:
  subdir:   "mupen64plus-video-gliden64/upstream"
  merged:   "9561a586e"
upstream:
  origin:   "https://github.com/gonetz/GLideN64.git"
  branch:   "master"
  commit:   "9561a586e"
git-subrepo:
  version:  "0.4.1"
  origin:   "https://github.com/ingydotnet/git-subrepo"
  commit:   "a04d8c2"

### CODE REVIEW

**Comment by bladeoner** [comment]
I had a local building issue which I resolved, the build is working.

**Comment by fzurita** [comment]
Please rebase with the master branch. I resolved some Travis issues and I want to make sure that your branch builds correctly.

**Comment by bladeoner** [comment]
I will do the branch rebase.

A few weeks a go I was busy converting the Travis build into a native Github Action build, I did that before with another project but I was stuck at some point and didn't find the time to look further into that. 

With the Github Action builds it enables us to have nightlies.

**Comment by bladeoner** [comment]
@fzurita rebasing has been done.

**Pull request merged**
