### PR TITLE
Removed ndk-bundle and change environment variable

### PR DESCRIPTION
**Pull request by bladeoner**
This reduces the Install step from almost 2 minutes to 16 seconds.

### CODE REVIEW

**Comment by bladeoner** [comment]
@fzurita build completed successfully, this closes #882

**Comment by fzurita** [comment]
Great, thanks, I'll merge it.

**Comment by bladeoner** [comment]
@fzurita thank you for your hard work on this project and enjoy New Year's Eve!

**Comment by fzurita** [comment]
Thanks, same to you!

**Comment by bladeoner** [comment]
Thank you!

**Pull request merged**
