### PR TITLE
Add -flto

### PR DESCRIPTION
**Pull request by loganmc10**
Adds Link Time Optimization. This is already enabled for the upstream modules (https://github.com/mupen64plus/mupen64plus-core/blob/master/projects/unix/Makefile#L130)

This slightly reduces the APK size, and should provide better performance. Compile time will increase, as the linking operations take longer.

If this is merged I'll submit a PR to GLideN64 with the changes as well.

### CODE REVIEW

**Comment by fzurita** [comment]
Hmm, interesting. I wonder how much performance it buys. Did you do any measurements? I have done some reading on it and in some cases it can reduce performance. But it really just needs to be tested.

Can you give Angrylion a shot and see if it's any faster? That's a good performance test that had zero dependence on the GPU.

**Comment by loganmc10** [comment]
No I didn't do much testing other than making sure that it worked. I'll test it out in a bit.

I don't think -flto would ever reduce performance unless it was done wrong (like passing -flto at compile time but not link time, something like that). But I'll test out angrylion in a bit

**Comment by loganmc10** [comment]
On my Shield Tablet I tested the Smash Bros opening with Angrylion. Both versions were the same (13 FPS). I also tested GoldenEye, same results (both were 25 FPS).

I think it's a fairly safe optimization, every instance I've read of it slowing down a program has been someone that hasn't passed the flags correctly (when using -flto, you have to pass the optimization flags to the linker, like -O3, if you don't when the linker runs, it will "undo" the -O3 you may have passed at compile time, which results in worse performance). This is why I set ```COMMON_LDFLAGS :=  $(COMMON_CFLAGS) $(COMMON_CPPFLAGS)```

**Comment by fzurita** [comment]
Cool, at least no performance loss. It shouldn't do any harm and they're is the potential for improvement. l'll merge. Thanks!

**Comment by fzurita** [comment]
FYI, this is causing linker errors with NDK 15. I'll try to figure out why it's failing soon.

**Comment by loganmc10** [comment]
Really? I built this with NDK 15 on Travis without issue (https://travis-ci.org/loganmc10/mupen64plus-ae/builds/245523406)

**Comment by fzurita** [comment]
Hmmm, interesting. It's giving me issues in Windows. The errors are kind of cryptic, so I'm going to have to add one line at a time to figure out which line is causing the error.

**Comment by fzurita** [comment]
If you are curious, this is what I'm getting:
```
> Build command failed.
Error while executing process C:\Users\Francisco\android-sdks\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\workspaces\mupen64plus-ae\app\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\workspaces\mupen64plus-ae\app\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-19 NDK_OUT=C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\workspaces\mupen64plus-ae\app\build\intermediates\ndkBuild\debug\lib APP_CPPFLAGS+=-fexceptions NDK_APPLICATION_MK:=src/main/jni/Application.mk -j4 C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libae-imports.so}
[armeabi-v7a] Compile++ thumb: ae-imports <= ae_imports.cpp
[armeabi-v7a] SharedLibrary  : libae-imports.so
Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: armv7-none-linux-android19
Thread model: posix
InstalledDir: C:\Users\Francisco\android-sdks\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin
Found candidate GCC installation: C:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi\4.9.x
Selected GCC installation: C:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x
Candidate multilib: thumb;@thumb
Candidate multilib: armv7-a;@armv7
Candidate multilib: armv7-a/thumb;@armv7@thumb
Candidate multilib: .;
Selected multilib: armv7-a;@armv7
 "C:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\\ld" --sysroot=C:/Users/Francisco/android-sdks/ndk-bundle/build//../platforms/android-19/arch-arm -X --eh-frame-hdr -m armelf_linux_eabi -shared -o C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libae-imports.so "C:/Users/Francisco/android-sdks/ndk-bundle/build//../platforms/android-19/arch-arm/usr/lib/../lib\\crtbegin_so.o" -LC:/Users/Francisco/android-sdks/ndk-bundle/build//../platforms/android-19/arch-arm/usr/lib "-LC:\\Users\\Francisco\\android-sdks\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\lib64\\clang\\5.0.300080\\lib\\linux\\arm" -LC:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/armv7-a -LC:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/../lib/armv7-a -LC:/Users/Francisco/android-sdks/ndk-bundle/build//../platforms/android-19/arch-arm/usr/lib/../lib -LC:/Users/Francisco/android-sdks/ndk-bundle/build//../platforms/android-19/arch-arm/usr/lib/arm-linux-androideabi/../../lib -LC:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/lib/armv7-a -LC:/Users/Francisco/android-sdks/ndk-bundle/build//../platforms/android-19/arch-arm/usr/lib -plugin "C:\\Users\\Francisco\\android-sdks\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin/../lib64/LLVMgold.so" -plugin-opt=mcpu=cortex-a8 -plugin-opt=O3 -soname libae-imports.so C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/ae-imports/ae_imports.o -lgcc --exclude-libs libgcc.a C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libgnustl_shared.so --fix-cortex-a8 --build-id --no-undefined -z noexecstack -z relro -z now --warn-shared-textrel --fatal-warnings -llog C:/Users/Francisco/android-sdks/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a -lc -lm -lstdc++ -lm -lgcc -ldl -lc -lgcc -ldl "C:/Users/Francisco/android-sdks/ndk-bundle/build//../platforms/android-19/arch-arm/usr/lib/../lib\\crtend_so.o"
C:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: C:\Users\Francisco\android-sdks\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin/../lib64/LLVMgold.so: could not load plugin library: unable to load dll
C:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/ae-imports/ae_imports.o:1:3: invalid character
C:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/ae-imports/ae_imports.o:1:3: syntax error, unexpected $end
C:/Users/Francisco/android-sdks/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs/ae-imports/ae_imports.o: not an object or archive
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:/workspaces/mupen64plus-ae/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libae-imports.so] Error 1
```

**Comment by fzurita** [comment]
Ok, did some googling. This is not supported in Windows right now:

https://github.com/android-ndk/ndk/issues/313

Maybe NDK 16, I'll re-open the pull request and revert the change.

**Comment by loganmc10** [comment]
Huh I guess that explains it then, thanks

**Comment by fzurita** [comment]
Hmm, I can't reopen after it's merged. I'll create an issue instead.

**Comment by fzurita** [comment]
NDK 16 is out, so maybe this is working now.

**Comment by fzurita** [comment]
I just tried it and it still doesn't work in windows.... oh well, in the mean time, I'll do this:

```
ifneq ($(HOST_OS),windows)
    COMMON_CFLAGS += -flto
    COMMON_LDFLAGS :=                   \
        $(COMMON_CFLAGS)                \
        $(COMMON_CPPFLAGS)              
endif
```

So at least linux gets the advantage.

**Pull request merged**
